### ISSUE TITLE
 using opencvforunity 2.4.6 always have the error -The type or namespace name 'Tracker' could not be found

### ISSUE THREAD

**Issue by tommywu052** [cookieofcode/LabAssistVision#11]
**Describe the bug**
Assets\LabAssistVision\Tracking\MILTracker.cs(19,44): error CS0246: The type or namespace name 'Tracker' could not be found (are you missing a using directive or an assembly reference?)

Assets\LabAssistVision\Tracking\KCFTracker.cs(18,28): error CS0246: The type or namespace name 'Tracker' could not be found (are you missing a using directive or an assembly reference?)
Assets\LabAssistVision\Tracking\TLDTracker.cs(26,44): error CS0246: The type or namespace name 'Tracker' could not be found (are you missing a using directive or an assembly reference?)

When I'm using opencvforunity 2.4.6 (only available on asset store). I always have the above error to build the scene. Is that due to the OpenCVforUnity version different from the 2.4.1 or something i'm missing ?

**Comment by tommywu052** [comment]
Closed since I got the 2.4.1 from official asset vendor, It works well on 2.4.1, tanks.

**Comment by Aki1380** [comment]
@tommywu052 
 Hey, I'm using opencvforunity 2.4.6 too.
 I want to use opencvforunity 2.4.1 to remove the error. But I don't know how to get it.
 Please tell me how to get it.
 Thank you for your cooperation.
